# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_resampling_app.ui'
#
# Created: Tue May 26 17:33:55 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 265)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../brain/codes/python_packages/PyQt-Image-Viewer/icons/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 278))
        self.centralwidget.setObjectName("centralwidget")
        self.input_groupBox = QtGui.QGroupBox(self.centralwidget)
        self.input_groupBox.setGeometry(QtCore.QRect(9, 9, 150, 110))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_groupBox.sizePolicy().hasHeightForWidth())
        self.input_groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.input_groupBox.setFont(font)
        self.input_groupBox.setObjectName("input_groupBox")
        self.formLayout = QtGui.QFormLayout(self.input_groupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.load_pushButton = QtGui.QPushButton(self.input_groupBox)
        self.load_pushButton.setObjectName("load_pushButton")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.load_pushButton)
        self.label = QtGui.QLabel(self.input_groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.label)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.input_groupBox)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.doubleSpinBox)
        self.output_groupBox = QtGui.QGroupBox(self.centralwidget)
        self.output_groupBox.setGeometry(QtCore.QRect(170, 10, 150, 110))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_groupBox.sizePolicy().hasHeightForWidth())
        self.output_groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.output_groupBox.setFont(font)
        self.output_groupBox.setObjectName("output_groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.output_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.output_pushButton = QtGui.QPushButton(self.output_groupBox)
        self.output_pushButton.setObjectName("output_pushButton")
        self.verticalLayout.addWidget(self.output_pushButton)
        self.run_pushButton = QtGui.QPushButton(self.output_groupBox)
        self.run_pushButton.setObjectName("run_pushButton")
        self.verticalLayout.addWidget(self.run_pushButton)
        self.plot_groupBox = QtGui.QGroupBox(self.centralwidget)
        self.plot_groupBox.setGeometry(QtCore.QRect(330, 10, 150, 110))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_groupBox.sizePolicy().hasHeightForWidth())
        self.plot_groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.plot_groupBox.setFont(font)
        self.plot_groupBox.setObjectName("plot_groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.plot_groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plotOriginal_pushButton = QtGui.QPushButton(self.plot_groupBox)
        self.plotOriginal_pushButton.setObjectName("plotOriginal_pushButton")
        self.verticalLayout_2.addWidget(self.plotOriginal_pushButton)
        self.plotResampled_pushButton = QtGui.QPushButton(self.plot_groupBox)
        self.plotResampled_pushButton.setObjectName("plotResampled_pushButton")
        self.verticalLayout_2.addWidget(self.plotResampled_pushButton)
        self.report_groupBox = QtGui.QGroupBox(self.centralwidget)
        self.report_groupBox.setGeometry(QtCore.QRect(10, 130, 471, 112))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.report_groupBox.sizePolicy().hasHeightForWidth())
        self.report_groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.report_groupBox.setFont(font)
        self.report_groupBox.setObjectName("report_groupBox")
        self.formLayout_2 = QtGui.QFormLayout(self.report_groupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.origSampleSize_label = QtGui.QLabel(self.report_groupBox)
        self.origSampleSize_label.setObjectName("origSampleSize_label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.origSampleSize_label)
        self.origMinMax_label = QtGui.QLabel(self.report_groupBox)
        self.origMinMax_label.setObjectName("origMinMax_label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.origMinMax_label)
        self.resSampleSize_label = QtGui.QLabel(self.report_groupBox)
        self.resSampleSize_label.setObjectName("resSampleSize_label")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.resSampleSize_label)
        self.resMinMax_label = QtGui.QLabel(self.report_groupBox)
        self.resMinMax_label.setObjectName("resMinMax_label")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.resMinMax_label)
        self.line = QtGui.QFrame(self.report_groupBox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.line)
        self.name_label = QtGui.QLabel(self.report_groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.name_label)
        self.date_label = QtGui.QLabel(self.report_groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.date_label.setFont(font)
        self.date_label.setObjectName("date_label")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.date_label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Resampling Point Cloud Data (PCD)", None, QtGui.QApplication.UnicodeUTF8))
        self.input_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.load_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Load PCD", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Resampling Factor", None, QtGui.QApplication.UnicodeUTF8))
        self.output_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Outputs", None, QtGui.QApplication.UnicodeUTF8))
        self.output_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Output Location", None, QtGui.QApplication.UnicodeUTF8))
        self.run_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Run Resampling", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.plotOriginal_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Plot Original PCD", None, QtGui.QApplication.UnicodeUTF8))
        self.plotResampled_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Plot Resampled PCD", None, QtGui.QApplication.UnicodeUTF8))
        self.report_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Report", None, QtGui.QApplication.UnicodeUTF8))
        self.origSampleSize_label.setText(QtGui.QApplication.translate("MainWindow", "Original sample size:", None, QtGui.QApplication.UnicodeUTF8))
        self.origMinMax_label.setText(QtGui.QApplication.translate("MainWindow", "Original min/max:", None, QtGui.QApplication.UnicodeUTF8))
        self.resSampleSize_label.setText(QtGui.QApplication.translate("MainWindow", "Resampled sample size:", None, QtGui.QApplication.UnicodeUTF8))
        self.resMinMax_label.setText(QtGui.QApplication.translate("MainWindow", "Resampled min/max:", None, QtGui.QApplication.UnicodeUTF8))
        self.name_label.setText(QtGui.QApplication.translate("MainWindow", "Prepared by: Reza Shafiei", None, QtGui.QApplication.UnicodeUTF8))
        self.date_label.setText(QtGui.QApplication.translate("MainWindow", "Date:", None, QtGui.QApplication.UnicodeUTF8))

